name: test
on:
  push:
    paths: [cmd/**, internal/**, pkg/**, go.sum]
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
          
      - name: Download dependencies
        run: go mod download
        
      - name: Run tests
        run: go test -v ./...
